# Generated by Django 5.2.7 on 2025-10-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
